Clean up setup script

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,32 +1,12 @@
 #!/usr/bin/env sh
 
-# Set up Middleman app.
-# Run this script immediately after cloning the codebase.
+# Run this script to setup the app
 
-# Check Ruby install
-if ! ruby --version | grep -Fq "$(< .ruby-version)"; then
-  printf 'You do not have the correct version of Ruby installed.\n'
+# Exit if any subcommand fails
+set -e
 
-  if command -v rbenv > /dev/null; then
-    if [ -d "$HOME/.plugins/ruby-build" ]; then
-      printf 'Updating to latest ruby-build...\n'
-      cd $HOME/.rbenv/plugins/ruby-build
-      git pull
-      cd -
-    else
-      printf 'Installing ruby-build...\n'
-      git clone https://github.com/sstephenson/ruby-build.git \
-        ~/.rbenv/plugins/ruby-build
-    fi
-
-    printf 'Installing the version of Ruby for this project...\n'
-    rbenv install
-  fi
-fi
-
-# Set up Ruby dependencies
+# Install dependencies
 bundle install
-
 npm install
 
 # Add binstubs to PATH. Your ~/.zshenv should include this line:
